In [25]:
import pandas as pd
import numpy as np

In [26]:
burned_fluxes = pd.read_excel('15B_Pond_BucketFlux_2023.xlsx')
unburned_fluxes = pd.read_excel('UB_Pond_BucketFlux_2023.xlsx')

In [27]:
burned_fluxes['pond'] = 'burned'
unburned_fluxes['pond'] = 'unburned'

In [28]:
fluxes_all_ch4 = pd.concat([burned_fluxes.loc[burned_fluxes['flux_type']=='CH4'], 
                            unburned_fluxes.loc[unburned_fluxes['flux_type']=='CH4']])
fluxes_all_ch4.loc[fluxes_all_ch4['flux_umol_m2_s1']<0, 'flux_umol_m2_s1'] = np.nan
fluxes_all_ch4['flux_mg_m2_d'] = fluxes_all_ch4['flux_umol_m2_s1'] * 1385.856
fluxes_all_ch4 = fluxes_all_ch4.drop(columns = ['flux_type'])
fluxes_all_ch4 = fluxes_all_ch4[['Date', 'Time', 'pond', 'Plot', 'flux_umol_m2_s1', 'flux_mg_m2_d', 'P_mbar', 'T_air', 'Slope (ppm/s)']]
fluxes_all_ch4

,Date,Time,pond,Plot,flux_umol_m2_s1,flux_mg_m2_d,P_mbar,T_air,Slope (ppm/s)
1,2023-07-07,10:48:00,burned,15BP1,0.001784,2.471938,1008.55,9.713,0.000238
3,2023-07-07,10:56:00,burned,15BP2,0.001964,2.722468,1008.45,10.298,0.000263
5,2023-07-15,11:30:00,burned,15BP1,0.001477,2.046743,1010.35,9.866,0.000197
7,2023-07-15,11:37:00,burned,15BP2,0.007136,9.889647,1010.35,9.866,0.000951
9,2023-07-20,16:14:00,burned,15BP1,0.025226,34.959920,1012.45,13.311,0.003397
11,2023-07-20,16:20:00,burned,15BP2,0.020561,28.494945,1012.15,13.620,0.002773
1,2023-07-02,10:45:00,unburned,UBP1,0.014419,19.982017,1008.05,15.432,0.001965
3,2023-07-02,10:55:00,unburned,UBP2,0.013821,19.153533,1008.65,15.888,0.001885
5,2023-07-10,10:12:00,unburned,UBP1,0.031819,44.097153,1004.55,8.904,0.004252
7,2023-07-10,10:17:00,unburned,UBP2,0.044272,61.354590,1004.55,8.904,0.005916
9,2023-07-17,10:05:00,unburned,UBP1,0.011159,15.464673,1012.35,14.574,0.001509
11,2023-07-17,10:11:00,unburned,UBP2,0.014965,20.739771,1012.35,14.574,0.002024

In [29]:
fluxes_all_co2 = pd.concat([burned_fluxes.loc[burned_fluxes['flux_type']=='CO2'], 
                            unburned_fluxes.loc[unburned_fluxes['flux_type']=='CO2']])
fluxes_all_co2.loc[fluxes_all_co2['flux_umol_m2_s1']<0, 'flux_umol_m2_s1'] = np.nan
fluxes_all_co2['flux_mg_m2_d'] = fluxes_all_co2['flux_umol_m2_s1'] * 3802.464
fluxes_all_co2 = fluxes_all_co2.drop(columns = ['flux_type'])
fluxes_all_co2 = fluxes_all_co2[['Date', 'Time', 'pond', 'Plot', 'flux_umol_m2_s1', 'flux_mg_m2_d', 'P_mbar', 'T_air', 'Slope (ppm/s)']]
fluxes_all_co2

,Date,Time,pond,Plot,flux_umol_m2_s1,flux_mg_m2_d,P_mbar,T_air,Slope (ppm/s)
0,2023-07-07,10:48:00,burned,15BP1,0.110872,421.586725,1008.55,9.713,0.0148
2,2023-07-07,10:56:00,burned,15BP2,0.212733,808.910530,1008.45,10.298,0.0284
4,2023-07-15,11:30:00,burned,15BP1,NaN,NaN,1010.35,9.866,-0.0294
6,2023-07-15,11:37:00,burned,15BP2,0.166515,633.166062,1010.35,9.866,0.0222
8,2023-07-20,16:14:00,burned,15BP1,1.011687,3846.904925,1012.45,13.311,0.1346
10,2023-07-20,16:20:00,burned,15BP2,1.063061,4042.252340,1012.15,13.620,0.1432
12,2023-07-28,10:14:00,burned,15BP1,0.805096,3061.350299,1011.85,12.472,0.1086
13,2023-07-28,10:21:00,burned,15BP2,0.358728,1364.050004,1011.75,12.529,0.0482
0,2023-07-02,10:45:00,unburned,UBP1,0.242193,920.928960,1008.05,15.432,0.0330
2,2023-07-02,10:55:00,unburned,UBP2,0.371583,1412.931560,1008.65,15.888,0.0506
4,2023-07-10,10:12:00,unburned,UBP1,0.190586,724.696428,1004.55,8.904,0.0261
6,2023-07-10,10:17:00,unburned,UBP2,0.793204,3016.127821,1004.55,8.904,0.1060
8,2023-07-17,10:05:00,unburned,UBP1,NaN,NaN,1012.35,14.574,-0.0242
10,2023-07-17,10:11:00,unburned,UBP2,0.181855,691.496098,1012.35,14.574,0.0246
12,2023-07-24,11:14:00,unburned,UBP1,6.406303,24359.738430,1007.35,13.403,0.8709
13,2023-07-24,11:19:00,unburned,UBP2,5.632410,21417.034881,1007.45,13.558,0.7625

In [32]:
fluxes_all = pd.merge(fluxes_all_ch4, fluxes_all_co2, on =['pond', 'Plot', 'Date'], suffixes=['_ch4', '_co2'], how='outer')
fluxes_all.to_csv('diffusion_bucket_fluxes_all.csv')

In [31]:
fluxes_all

,Date,Time_ch4,pond,Plot,flux_umol_m2_s1_ch4,flux_mg_m2_d_ch4,P_mbar_ch4,T_air_ch4,Slope (ppm/s)_ch4,Time_co2,flux_umol_m2_s1_co2,flux_mg_m2_d_co2,P_mbar_co2,T_air_co2,Slope (ppm/s)_co2
0,2023-07-07,10:48:00,burned,15BP1,0.001784,2.471938,1008.55,9.713,0.000238,10:48:00,0.110872,421.586725,1008.55,9.713,0.0148
1,2023-07-07,10:56:00,burned,15BP2,0.001964,2.722468,1008.45,10.298,0.000263,10:56:00,0.212733,808.910530,1008.45,10.298,0.0284
2,2023-07-15,11:30:00,burned,15BP1,0.001477,2.046743,1010.35,9.866,0.000197,11:30:00,NaN,NaN,1010.35,9.866,-0.0294
3,2023-07-15,11:37:00,burned,15BP2,0.007136,9.889647,1010.35,9.866,0.000951,11:37:00,0.166515,633.166062,1010.35,9.866,0.0222
4,2023-07-20,16:14:00,burned,15BP1,0.025226,34.959920,1012.45,13.311,0.003397,16:14:00,1.011687,3846.904925,1012.45,13.311,0.1346
5,2023-07-20,16:20:00,burned,15BP2,0.020561,28.494945,1012.15,13.620,0.002773,16:20:00,1.063061,4042.252340,1012.15,13.620,0.1432
6,2023-07-02,10:45:00,unburned,UBP1,0.014419,19.982017,1008.05,15.432,0.001965,10:45:00,0.242193,920.928960,1008.05,15.432,0.0330
7,2023-07-02,10:55:00,unburned,UBP2,0.013821,19.153533,1008.65,15.888,0.001885,10:55:00,0.371583,1412.931560,1008.65,15.888,0.0506
8,2023-07-10,10:12:00,unburned,UBP1,0.031819,44.097153,1004.55,8.904,0.004252,10:12:00,0.190586,724.696428,1004.55,8.904,0.0261
9,2023-07-10,10:17:00,unburned,UBP2,0.044272,61.354590,1004.55,8.904,0.005916,10:17:00,0.793204,3016.127821,1004.55,8.904,0.1060
10,2023-07-17,10:05:00,unburned,UBP1,0.011159,15.464673,1012.35,14.574,0.001509,10:05:00,NaN,NaN,1012.35,14.574,-0.0242
11,2023-07-17,10:11:00,unburned,UBP2,0.014965,20.739771,1012.35,14.574,0.002024,10:11:00,0.181855,691.496098,1012.35,14.574,0.0246
12,2023-07-28,NaN,burned,15BP1,NaN,NaN,NaN,NaN,NaN,10:14:00,0.805096,3061.350299,1011.85,12.472,0.1086
13,2023-07-28,NaN,burned,15BP2,NaN,NaN,NaN,NaN,NaN,10:21:00,0.358728,1364.050004,1011.75,12.529,0.0482
14,2023-07-24,NaN,unburned,UBP1,NaN,NaN,NaN,NaN,NaN,11:14:00,6.406303,24359.738430,1007.35,13.403,0.8709
15,2023-07-24,NaN,unburned,UBP2,NaN,NaN,NaN,NaN,NaN,11:19:00,5.632410,21417.034881,1007.45,13.558,0.7625