In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
path_to_burned_soil_2022_23 = '15B_FP_ST-SM_Profile_22-23.xlsx'
path_to_unburned_soil_2022_23 = 'UB_FP_ST-SM_Profile_22-23.xlsx'

path_to_burned_soil_24 = '15B_FP_ST-SM_Profile_24.xlsx'
path_to_unburned_soil_24 = 'UB_FP_ST-SM_Profile_24.xlsx'

burned_soil_2022_23 = pd.read_excel(path_to_burned_soil_2022_23, parse_dates=['Date Time, GMT-09:00']).rename(columns={'Date Time, GMT-09:00': 'Date'})
unburned_soil_2022_23 = pd.read_excel(path_to_unburned_soil_2022_23, parse_dates=['Date Time, GMT-09:00']).rename(columns={'Date Time, GMT-09:00': 'Date'})

burned_soil_24 = pd.read_excel(path_to_burned_soil_24, parse_dates=['Date Time, GMT-09:00']).rename(columns={'Date Time, GMT-09:00': 'Date'})
unburned_soil_24 = pd.read_excel(path_to_unburned_soil_24, parse_dates=['Date Time, GMT-09:00']).rename(columns={'Date Time, GMT-09:00': 'Date'})

burned_soil_2022_23.head()

,Date,5 cm ST (°C),10 cm ST (°C),20 cm ST (°C),30 cm ST (°C),50 cm ST (°C),100 cm ST (°C),125 cm ST (°C),10 cm SM (m³/m³),30 cm SM (m³/m³)
0,2022-06-29 00:00:00,9.163,8.170,3.670,1.180,0.024,-0.255,-0.199,NaN,NaN
1,2022-06-29 00:30:00,8.916,8.020,3.670,1.208,0.024,-0.255,-0.199,NaN,NaN
2,2022-06-29 01:00:00,8.717,7.870,3.696,1.208,0.024,-0.255,-0.199,NaN,NaN
3,2022-06-29 01:30:00,8.543,7.745,3.670,1.208,0.024,-0.255,-0.199,NaN,NaN
4,2022-06-29 02:00:00,8.519,7.670,3.670,1.208,0.024,-0.255,-0.199,NaN,NaN

In [22]:
burned_soil_2022_23_daily_mean = burned_soil_2022_23.groupby(by=burned_soil_2022_23['Date'].dt.date).mean()
burned_soil_2022_23_daily_std = burned_soil_2022_23.groupby(by=burned_soil_2022_23['Date'].dt.date).std()
burned_soil_2024_daily_mean = burned_soil_24.groupby(by=burned_soil_24['Date'].dt.date).mean()
burned_soil_2024_daily_std = burned_soil_24.groupby(by=burned_soil_24['Date'].dt.date).std()

burned_soil_2022_23_daily = pd.merge(burned_soil_2022_23_daily_mean, burned_soil_2022_23_daily_std, left_index=True, right_index=True, suffixes=('_mean', '_std')).reset_index()
burned_soil_2022_23_daily['pond'] = 'burned'

burned_soil_2024_daily = pd.merge(burned_soil_2024_daily_mean, burned_soil_2024_daily_std, left_index=True, right_index=True, suffixes=('_mean', '_std')).reset_index()
burned_soil_2024_daily['pond'] = 'burned'


unburned_soil_2022_23_daily_mean = unburned_soil_2022_23.groupby(by=unburned_soil_2022_23['Date'].dt.date).mean()
unburned_soil_2022_23_daily_std = unburned_soil_2022_23.groupby(by=unburned_soil_2022_23['Date'].dt.date).std()

unburned_soil_2024_daily_mean = unburned_soil_24.groupby(by=unburned_soil_24['Date'].dt.date).mean()
unburned_soil_2024_daily_std = unburned_soil_24.groupby(by=unburned_soil_24['Date'].dt.date).std()

unburned_soil_2022_23_daily = pd.merge(unburned_soil_2022_23_daily_mean, unburned_soil_2022_23_daily_std, left_index=True, right_index=True, suffixes=('_mean', '_std')).reset_index()
unburned_soil_2022_23_daily['pond'] = 'unburned'

unburned_soil_2024_daily = pd.merge(unburned_soil_2024_daily_mean, unburned_soil_2024_daily_std, left_index=True, right_index=True, suffixes=('_mean', '_std')).reset_index()
unburned_soil_2024_daily['pond'] = 'unburned'

soil_data = pd.concat([burned_soil_2022_23_daily, unburned_soil_2022_23_daily, burned_soil_2024_daily, unburned_soil_2024_daily])

/tmp/ipykernel_4100/2985939912.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  burned_soil_2022_23_daily_mean = burned_soil_2022_23.groupby(by=burned_soil_2022_23['Date'].dt.date).mean()
/tmp/ipykernel_4100/2985939912.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  burned_soil_2022_23_daily_std = burned_soil_2022_23.groupby(by=burned_soil_2022_23['Date'].dt.date).std()
/tmp/ipykernel_4100/2985939912.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  burned_soil_2024_daily_mean = burned_soil_24.groupby(by=burned_soil_24['Date'].dt.date).mean()
/tmp/ipykernel_4100/2985939912.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  burned_soil_2024_daily_std = burned_soil_24.groupby(by=burned_soil_24['Date'].dt.date).std()
/tmp/ipykernel_4100/2985939912.py:13: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  unburned_soil_2022_23_daily_mean = unburned_soil_2022_23.groupby(by=unburned_soil_2022_23['Date'].dt.date).mean()
/tmp/ipykernel_4100/2985939912.py:14: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  unburned_soil_2022_23_daily_std = unburned_soil_2022_23.groupby(by=unburned_soil_2022_23['Date'].dt.date).std()
/tmp/ipykernel_4100/2985939912.py:16: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  unburned_soil_2024_daily_mean = unburned_soil_24.groupby(by=unburned_soil_24['Date'].dt.date).mean()
/tmp/ipykernel_4100/2985939912.py:17: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  unburned_soil_2024_daily_std = unburned_soil_24.groupby(by=unburned_soil_24['Date'].dt.date).std()

In [23]:
soil_data.to_csv('YKD_soil_data_2022_24.csv', index=False)